language: java
dist: trusty
jdk:
  - openjdk8
  #- openjdk9
  #- openjdk10
  - openjdk11
script: ./gradlew check
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
